baseURL: "https://modernman.nz/"
languageCode: en-us
title: Modern Man Barbershop
theme: tella

params:
  logo:
    main: "/img/logo.webp"
    alt: "modern man barbershop logo"
    size: "logo"
     
  googleAnalytics: GTDSQTLWR0
  defaultTheme: light
  disableThemeToggle: true

  homeInfoParams:
      Title: Modern Man Barbershop - Christchurch City Barber and Stylists
      Content: The Modern Man Barbershop, located in the Christchurch CBD at the Crossing next to Barkers, is a specialist barbershop dedicated to styling the modern men of Christchurch.
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/”
  Name: twitter
  Url: “https://twitter.com/”

  cover: 
      linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true




menu: 
  main: 

    - identifier: groomsman
      name: Groomsman Package
      url: /pages/grooms/
      weight: 1

    - identifier: shop
      name: Mens Styling Products
      url: /pages/shop/
      weight: 2

    - identifier: directions
      name: Directions - 690 Colombo St
      url: https://goo.gl/maps/kyqyg2kQNch4SWHu6
      target: _blank
      weight: 3

    - identifier: number
      name: 021 0801 3804
      url: tel:021 0801 3804
      weight: 4

  footer:
    - name: Home
      url: /
      weight: 1

    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false