baseURL: "https://www.modernmannz.com"
languageCode: en-us
title: Modern Man Barbershop
theme: tella

params:
  logo: 
    src: "/img/modern-barbershop-chch-logo.webp"
    alt: "modern man barbershop logo"
  googleAnalytics: GTDSQTLWR0
  defaultTheme: light
  disableThemeToggle: true

  homeInfoParams:
      Title: Modern Man Barbershop - Christchurch City Barber and Stylists
      Content: The Modern Man Barbershop, located in the Christchurch CBD at the Crossing next to Barkers, is a specialist barbershop dedicated to styling the modern men of Christchurch.
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/”
  Name: twitter
  Url: “https://twitter.com/”

  cover: 
      linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true




menu: 
  main: 
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10

    - identifier: groomsman
      name: Groomsman Package
      url: /pages/groomsman/
      weight: 20

    - identifier: shop
      name: Shop Mens Styling Products
      url: /pages/shop/
      weight: 30

    - identifier: directions
      name: 690 Colombo St - Get Directions
      url: https://goo.gl/maps/kyqyg2kQNch4SWHu6
      weight: 40

    - identifier: number
      name: 0800 83 83 83
      url: tel:0800 83 83 83
      weight: 90

    - identifier: book-now
      name: Book now
      url: https://bookings.gettimely.com/modernman/book?uri=https%3A%2F%2Fbook.gettimely.com%2FBooking%2FLocation%2F200736%3Fmobile%3DTrue%26params%3D%25253fclient-login%25253dtrue
      weight: 100



markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false